run-dist: #Launch of the program
	./build/install/app/bin/app

build: #A build of the app
	./gradlew installDist

clean:
	./gradlew clean

lint: #Chech a style of code via Checkstyle
	./gradlew checkstyleMain
